#!/usr/bin/python
import os
import sys

if __name__ == "__main__":

    if len(sys.argv) < 2:
        sys.stderr.write("Usage: %s CMD ARGS...\n" % (sys.argv[0]))

    args = sys.argv[1:]

    try:
        process_id = os.fork()
    except OSError as e:
        self.logger.error("Unable to fork, errno: {0}".format(e.errno))
        sys.exit(1)

    if process_id != 0:
        os._exit(0)

    res = os.execvp(args[0], list(args))
