#! /bin/bash

### BEGIN INIT INFO
# Provides:	        pool-controller
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	Smart Pool Pump Functionality
### END INIT INFO


set -e

name='pool-controller'
daemonize="daemonize"
bin="$name"
data_dir="/var/cache/homekit"
args="-p -data_dir=$data_dir"
pidfile="/tmp/$name.pid"
log="/tmp/pc.log"
bindir="/usr/local/bin"

#Redirect all output syslog
exec 1> >(logger -t $name -p daemon.info) 2>&1

export PATH="${PATH:+$PATH:}/usr/local/bin"

test -x $bindir/$daemonize || exit 0
test -x $bindir/$bin || exit 0
umask 022

check_data_dir() {
    # Create the Data empty dir if necessary
    if [ ! -d $data_dir ]; then
	mkdir -p $data_dir
	chmod 0755 $data_dir
    fi
    cd $data_dir
}

start_proc() {
    check_data_dir
    cd $rundir
    if $daemonize $bin $args -pid=$pidfile; then
	echo "Starting $name: Success"
    else
        echo "Starting $name: Failed"
    fi
}

stop_proc() {
    if [ -f $pidfile ]; then
	pid=`cat $pidfile`
    else
	pid=`pgrep $name`
    fi

    if kill -2 $pid; then
	echo "Stopping $name: Success"
    else
	echo "Stopping $name: Failed"
    fi
}

case "$1" in
    start)
	start_proc
	;;
    stop)
	stop_proc
	;;
    restart)
	stop_proc
	sleep 2
	start_proc
	;;
    *)
	echo "Usage: /etc/init.d/$name {start|stop|restart}"
	exit 1
esac

exit 0
