#! /bin/sh

### BEGIN INIT INFO
# Provides:	        pi-go-homekit
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	Smart PoolPump Functionality
### END INIT INFO

set -e

# /etc/init.d/poold: start and stop the poold daemon
name='pool-controller'
bin='/usr/local/bin/daemonize.py /usr/local/bin/$name'
args='-p -data_dir="$data_dir"'
data_dir="/var/cache/homekit"
pidfile="/tmp/$name.pid"

test -x $bin || exit 0
umask 022
export PATH="${PATH:+$PATH:}/usr/local/bin"

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_data_dir() {
    # Create the Data empty dir if necessary
    if [ ! -d $data_dir ]; then
	mkdir -p $data_dir
	chmod 0755 $data_dir
    fi
    cd $data_dir
}

start() {
    check_data_dir
    cd $rundir
    log_daemon_msg "Starting" "$name" || true
    log_daemon_msg "Starting" "$name" || true
	if start-stop-daemon --start --pidfile $pid --exec $bin -p -data_dir="$data_dir"&; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
}

stop() {
    log_daemon_msg "Stopping" "$name" || true
	if start-stop-daemon --stop --pidfile $pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi

}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;

    restart)
	stop
	start
	;;

    status)
	status_of_proc -p `cat $pidfile` $bin && exit 0 || exit $?
	;;

    *)
	log_action_msg "Usage: /etc/init.d/$name {start|stop|restart|status}" || true
	exit 1
esac

exit 0
