version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -u -t -d ./...
  test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go -v test ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test